{% set version = "1.1.1" %}

package:
  name: deps
  version: {{ version }}

source:
  url: https://github.com/ESSS/deps/archive/v{{ version }}.tar.gz
  sha256: 4969988de38ae6c7e54806a14f3713e7346d3c77283f60881feaf432457ecc18

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - deps = deps.deps_cli:main_func

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - colorama
    - jinja2
    - pyyaml
    - futures  # [py27]

test:
  requires:
    - pytest >=3
    - pytest-mock
    - future
  imports:
    - deps
  commands:
    - deps --help
    - deps --version
    - python -m deps --version
    - pytest source/python
  source_files:
    - source/python

about:
  home: https://github.com/ESSS/deps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'An utility to execute commands on multiple projects.'
  doc_url: https://github.com/ESSS/deps
  dev_url: https://github.com/ESSS/deps

extra:
  recipe-maintainers:
    - tadeu
    - nicoddemus
    - prusse-martin
