{% set version = "1.3.0" %}

package:
  name: deps
  version: {{ version }}

source:
  url: https://github.com/ESSS/deps/archive/v{{ version }}.tar.gz
  sha256: e473bdb58a2574cd80166b10a15754bdc168aa2e69043d237a2fc0b2c1c2084c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - deps = deps.deps_cli:main_func

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - click
    - colorama
    - jinja2
    - pyyaml

test:
  requires:
    - pytest >=3
    - pytest-mock
  imports:
    - deps
  commands:
    - deps --help
    - deps --version
    - python -m deps --version
    - pytest --pyargs deps -p deps.fixtures

about:
  home: https://github.com/ESSS/deps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An utility to execute commands on multiple projects.
  doc_url: https://github.com/ESSS/deps
  dev_url: https://github.com/ESSS/deps

extra:
  recipe-maintainers:
    - tadeu
    - nicoddemus
    - prusse-martin
