{% set python_min = "3.10" %}
{% set version = "1.5.1" %}

package:
  name: deps
  version: {{ version }}

source:
  url: https://github.com/ESSS/deps/archive/v{{ version }}.tar.gz
  sha256: ad350213e62b98909d853d6dd18cf16a0ea4a26b7cda6f90c01e3430b70c33f8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - deps = deps.deps_cli:main_func

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build >=0.8,<0.9.0
  run:
    - python >={{ python_min }}
    - click >=7.0
    - colorama >=0.4
    - importlib-metadata >=8.7.0
    - jinja2 >=3.1
    - pyyaml >=6.0.2
    - tomli >=2.2.1
    - typing_extensions

test:
  requires:
    # click 8.2.1 has a bug regarding bool flags and env vars: https://github.com/pallets/click/pull/2956
    # this breaks test_force_color in our test suite.
    - click >=8.1,!=8.2.*
    - pytest >=8.4.1
    - pytest-mock>=3.14.1
    - python {{ python_min }}
  imports:
    - deps
  commands:
    - deps --help
    - deps --version
    - python -m deps --version
    - pytest --pyargs deps -p deps.fixtures

about:
  home: https://github.com/ESSS/deps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An utility to execute commands on multiple projects.
  doc_url: https://github.com/ESSS/deps
  dev_url: https://github.com/ESSS/deps

extra:
  recipe-maintainers:
    - tadeu
    - nicoddemus
    - prusse-martin
