{% set version = "1.3.1" %}

package:
  name: deps
  version: {{ version }}

source:
  url: https://github.com/ESSS/deps/archive/v{{ version }}.tar.gz
  sha256: 2c04846aeef3d2bed632348fc7c4db5b95c2baea129f2442b2713585394d5085

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - deps = deps.deps_cli:main_func

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - click
    - colorama
    - jinja2
    - pyyaml

test:
  requires:
    - pytest >=3
    - pytest-mock
  imports:
    - deps
  commands:
    - deps --help
    - deps --version
    - python -m deps --version
    - pytest --pyargs deps -p deps.fixtures

about:
  home: https://github.com/ESSS/deps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An utility to execute commands on multiple projects.
  doc_url: https://github.com/ESSS/deps
  dev_url: https://github.com/ESSS/deps

extra:
  recipe-maintainers:
    - tadeu
    - nicoddemus
    - prusse-martin
