{% set version = "1.2.0" %}

package:
  name: deps
  version: {{ version }}

source:
  url: https://github.com/ESSS/deps/archive/v{{ version }}.tar.gz
  sha256: 2c6d757715f1f2f848ab3b3c4ec36bbfeb3f98334c989c0acdd75a3b3fd9d2d7

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - deps = deps.deps_cli:main_func

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - colorama
    - jinja2
    - pyyaml
    - futures  # [py27]

test:
  requires:
    - pytest >=3
    - pytest-mock
    - future
  imports:
    - deps
  commands:
    - deps --help
    - deps --version
    - python -m deps --version
    - pytest --pyargs deps -p deps.fixtures
  source_files:
    - pytest.ini
    - source/python

about:
  home: https://github.com/ESSS/deps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An utility to execute commands on multiple projects.
  doc_url: https://github.com/ESSS/deps
  dev_url: https://github.com/ESSS/deps

extra:
  recipe-maintainers:
    - tadeu
    - nicoddemus
    - prusse-martin
