schema_version: 1

context:
  version: "1.8.0"

package:
  name: deps
  version: ${{ version }}

source:
  url: https://github.com/ESSS/deps/archive/v${{ version }}.tar.gz
  sha256: 4c88aaf42d801b36f09270a06f253c0044b27a55c8003c4c53b816fc9950adf2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  python:
    entry_points:
      - deps = deps.deps_cli:main_func

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build >=0.8,<0.9.0
  run:
    - python >=${{ python_min }}
    - click >=8.5
    - importlib-metadata >=8.7.0
    - jinja2 >=3.1
    - pyyaml >=6.0.2
    - tomli >=2.2.1
    - typing_extensions

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - deps
      pip_check: false
  - requirements:
      run:
        - pytest >=8.4.1
        - pytest-mock >=3.14.1
    script:
      - deps --help
      - deps --version
      - python -m deps --version
      - pytest --pyargs deps -p deps.fixtures

about:
  license: MIT
  license_file: LICENSE
  summary: An utility to execute commands on multiple projects.
  homepage: https://github.com/ESSS/deps
  repository: https://github.com/ESSS/deps
  documentation: https://github.com/ESSS/deps

extra:
  recipe-maintainers:
    - tadeu
    - nicoddemus
    - prusse-martin
