travis:
  secure:
    BINSTAR_TOKEN: IZIZw+BBSB5reDkrezI0biVr0VKHZAbM1UZblvEIDMDmDqNaqw88KWXFsqM8xUHY/W09IghlnVGwCq9qA5Zjn0KyQex7lr9xnQZlx6vAp+D3nzty/rE0ub5TqbsfRUbrdRwCSoH10CB6O7LVrDBFxWfVgbgeqZ9oUOB/1fQIjlAaM+d3C7/T6LPl3aoFt17BL0Ji5gdirwRWlGvv91WhMOcZkLyyl1FVSzUgAsvmndwbnLjjhhpBSY43/GG0z60I3oCQRSCl1TYeBw1yt8+qJiHgQFz6vzqZI6XlN0xEkbW7sURxqq0r4bkNTm0mvWg07kp4CQAOEPbD5zltn2zAvL8eN4Qh5DiEZyTJyNP4Y97I669Ki83pNlxBzgaKQLwLzR4Qq9PmcmLDzszg+bWF0MirjVD6xLBYXUZZqVRMtUYHdtgQKno7OWUrbLeW3bb2cH/kmF79nlSmIhDMQ8D3rO6qNB7pRmOcoZcDosbm1JkriF31fePfL3wjWBFPsF7p8WONRfU3LLA5G+M6pGilM3obrm0reBhXMrFkN8siO94QqP9taj7+aS3iO59BZbjfk+/Ti8nWHdZHC9jtvPa9Zb/6mFYSpfS6B70s9KAOV7omgfwrzOZGE6rbb63+oQbwDFKZNguWdCs30YUOVgMhNqc0/uVnhC/HfmhVmnTqgjA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
